# Generated by Django 6.0 on 2026-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogView',
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
